title: Delong's Story Book
description: Developer stories I saw, I heard, and also I am part of.
show_info: true
twitter_url: https://twitter.com/DelongGao
google_analytics:
theme:
gems:
  - jekyll-paginate
paginate: 5
